name: Build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint-build-sh:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: |
        sudo apt-get update -y
        sudo apt-get install shellcheck -y

    - name: Lint
      run: shellcheck --shell=sh --exclude=SC2086 --norc ./build.sh;

  build-linux:
    strategy:
      matrix:
        cc: [gcc, clang]

    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install libglfw3-dev python3 python3-pip gcc clang -y

    - name: Install Python Modules
      run: python3 -m pip install --upgrade Pillow

    - name: Generate Build Files & Build
      env:
        CC: "${{ matrix.cc == 'gcc' && 'gcc' || 'clang' }}"
        CXX: "${{ matrix.cc == 'gcc' && 'g++' || 'clang++' }}"
        LD: "${{ matrix.cc == 'gcc' && 'g++' || 'clang++' }}"
      run: |
        ./build.sh assets
        ./build.sh release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-linux-${{ matrix.cc }}
        if-no-files-found: error
        path: ./build/csprite

  build-windows:
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Change Git Config
      run: git config --global core.autocrlf input

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python Modules
      run: pip install --upgrade Pillow

    - name: Setup BusyBox
      run: curl.exe -L "https://frippery.org/files/busybox/busybox.exe" -o ./busybox.exe

    - name: Generate Build Files & Build
      shell: cmd
      run: |
        # https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md#visual-studio-enterprise-2022
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        .\busybox.exe sh -c "export CC=clang; export CXX=clang++; export LD=clang++; ./build.sh assets && ./build.sh release"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        if-no-files-found: error
        path: ./build/csprite.exe
