name: Build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint-build-sh:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: |
        sudo apt-get update -y
        sudo apt-get install shellcheck -y

    - name: Lint
      run: |
        shellcheck --shell=sh ./build.sh

  build-linux:
    strategy:
      matrix:
        cc: [gcc, clang]

    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install libglfw3-dev make python3 python3-pip gcc clang -y

    - name: Install Python Modules
      run: python3 -m pip install --upgrade Pillow

    - name: Generate Build Files
      run: make gen-assets

    - name: Build (gcc)
      if: ${{ matrix.cc == 'gcc' }}
      run: make all -j4 BUILD_TYPE=release CC=gcc CXX=g++

    - name: Build (clang)
      if: ${{ matrix.cc == 'clang' }}
      run: make all -j4 BUILD_TYPE=release CC=clang CXX=clang++

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-linux-${{ matrix.cc }}
        if-no-files-found: error
        path: ./build/csprite

  build-windows:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Change Git Config
      run: git config --global core.autocrlf input

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python Modules
      run: pip install --upgrade Pillow

    - name: Setup Cygwin
      uses: cygwin/cygwin-install-action@master
      with:
        platform: x86_64
        packages: wget unzip make git curl busybox

    - name: Generate Build Files & Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        make gen-assets
        make all -j4 BUILD_TYPE=release CC=clang CXX=clang++

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-windows
        if-no-files-found: error
        path: ./build/csprite.exe
