name: Build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Deps (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install gcc libglfw3-dev make python3 python3-pip clang -y

    - name: Install Python Deps
      run: |
        python3 -m pip install --upgrade Pillow

    - name: Generate Build Files & Build (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        make gen-assets
        make all -j4 BUILD_TYPE=release
        mv build/csprite ./csprite-gcc
        make clean gen-assets
        make all -j4 BUILD_TYPE=release CC=clang CXX=clang++
        mv build/csprite ./csprite-clang

    - name: Upload Artifacts (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        if-no-files-found: error
        path: |
          ./csprite-gcc
          ./csprite-clang
