name: Build
on:
  push:
    branches: [ c ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x64
            cc: gcc
            cxx: g++
            pkgs: gcc libglfw3-dev

          - os: ubuntu-22.04
            arch: x32
            cc: gcc
            cxx: g++
            pkgs: gcc-multilib g++-multilib libglfw3-dev:i386
            flags: "-m32"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Deps (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y
        sudo apt-get install ${{ matrix.pkgs }} make python3 python3-pip -y

    - name: Install Python Deps
      run: |
        python3 -m pip install --upgrade Pillow

    - name: Generate Build Files & Build (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        export CC=${{ matrix.cc }}
        export CXX=${{ matrix.cxx }}
        export CLI_CFLAGS=${{ matrix.flags }}
        export CLI_LFLAGS=${{ matrix.flags }}
        make gen-assets
        make all -j4 BUILD_TYPE=release
        cp -r ./build/csprite ./csprite

    - name: Upload Artifacts (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: actions/upload-artifact@v3
      with:
        name: linux-${{ matrix.arch }}
        if-no-files-found: error
        path: ./csprite
