name: Continous Build Action
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  generate-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Generate Asset
      run: |
        python3 -m pip install --upgrade Pillow
        python3 -m pip install --upgrade numpy
        python3 tools/create_icons.py
        python3 tools/create_assets.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: generated_assets
        path: ./src/assets/
        if-no-files-found: error

  linux-x86_64:
    needs: [generate-assets]
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: generated_assets
        path: ./src/assets/

    - name: Install GLFW3, Git & Scons
      run: |
        sudo apt-get install libglfw3 libglfw3-dev git scons

    - name: Build
      run: make release

    - name: Strip & rename
      run: strip ./csprite && mv ./csprite csprite.elf

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: csprite.elf
        if-no-files-found: error

  linux_i686:
    needs: [generate-assets]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/download-artifact@v2
      with:
        name: generated_assets
        path: ./src/assets/

    - name: Setup Ubuntu 18.04 x86
      uses: paulproteus/ubuntu-18.04-x86@0.1
      with:
        command: |
          apt-get update -y
          apt-get install -y libglfw3 libglfw3-dev pkg-config git libgtk-3-dev scons clang
          CC=clang make release
          mv csprite csprite-i686.elf

    - name: Exit if file not exists
      run: |
        if [ ! -e ./csprite-i686.elf ]; then
            echo "'csprite-i686.elf' executable not found"
            exit 1
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-i686
        path: ./csprite-i686.elf
        if-no-files-found: error

  windows-x86_64:
    needs: [generate-assets]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: mingw-w64-x86_64-clang mingw-w64-x86_64-glfw mingw-w64-x86_64-python scons make git

      - uses: actions/download-artifact@v2
        with:
          name: generated_assets
          path: ./src/assets/

      - name: Generate RC
        run: |
          python3 tools/create_rc.py --arch=x86_64 --majver=0 --minver=0 --patver=0

      - name: Build & Rename
        run: |
          CC=clang make release
          mv csprite.exe csprite-x86_64.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win-x86_64
          path: csprite-x86_64.exe
          if-no-files-found: error

  windows-i686:
    needs: [generate-assets]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: mingw-w64-i686-binutils mingw-w64-i686-clang mingw-w64-i686-glfw mingw-w64-x86_64-python scons make git

      - uses: actions/download-artifact@v2
        with:
          name: generated_assets
          path: ./src/assets/

      - name: Generate Assets
        run: |
          python3 tools/create_rc.py --arch=i686 --majver=0 --minver=0 --patver=0

      - name: Build & Rename
        run: |
          CC=clang make release
          mv csprite.exe csprite-i686.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win-i686
          path: csprite-i686.exe
          if-no-files-found: error

  osx_x86_64:
    needs: [generate-assets]
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install scons, dylibbundler, pillow & glfw3
      run: |
        brew install scons dylibbundler glfw

    - uses: actions/download-artifact@v2
      with:
        name: generated_assets
        path: ./src/assets/

    - name: Build
      run: make release

    - name: Generate .icns
      run: |
        mkdir csprite.iconset
        sips -z 16 16     data/icon-512.png --out csprite.iconset/icon_16x16.png
        sips -z 32 32     data/icon-512.png --out csprite.iconset/icon_16x16@2x.png
        sips -z 32 32     data/icon-512.png --out csprite.iconset/icon_32x32.png
        sips -z 64 64     data/icon-512.png --out csprite.iconset/icon_32x32@2x.png
        sips -z 128 128   data/icon-512.png --out csprite.iconset/icon_128x128.png
        sips -z 256 256   data/icon-512.png --out csprite.iconset/icon_128x128@2x.png
        sips -z 256 256   data/icon-512.png --out csprite.iconset/icon_256x256.png
        sips -z 512 512   data/icon-512.png --out csprite.iconset/icon_256x256@2x.png
        sips -z 512 512   data/icon-512.png --out csprite.iconset/icon_512x512.png
        cp data/icon-512.png csprite.iconset/icon_512x512@2x.png
        iconutil -c icns -o csprite.icns csprite.iconset
        rm -R csprite.iconset

    - name: Create Apple Bundle
      run: |
        mkdir csprite.app
        mkdir csprite.app/Contents
        mkdir csprite.app/Contents/libs
        mkdir csprite.app/Contents/MacOS
        mkdir csprite.app/Contents/Resources
        cp ./csprite ./csprite.app/Contents/MacOS/
        cp ./csprite.icns ./csprite.app/Contents/Resources/csprite.icns
        cp ./data/Info.plist ./csprite.app/Contents/

    - name: Put Dylibs
      run: |
        dylibbundler -od -b -ns -x ./csprite.app/Contents/MacOS/csprite -d ./csprite.app/Contents/libs/

    - name: Create Zip
      run: zip -r csprite-osx.zip ./csprite.app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx_binary
        path: ./csprite-osx.zip
        if-no-files-found: error
