name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            arch: x64
            gen_short_name: "vs17_2022"
            gen_cmake_name: "Visual Studio 17 2022"

          - os: windows-2022
            arch: Win32
            gen_short_name: "vs17_2022"
            gen_cmake_name: "Visual Studio 17 2022"

          - os: ubuntu-22.04
            cc: gcc
            cxx: g++
            image: i386/ubuntu:latest
            arch: x64

          - os: ubuntu-22.04
            cc: gcc
            cxx: g++
            image: amd64/ubuntu:latest
            arch: x32

          - os: macos-12
            arch: x86_64
            gen: Xcode

          - os: macos-12
            arch: arm64
            gen: Xcode

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Install Deps (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install git gcc xorg-dev cmake ninja-build python3 python3-pip

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Lint Info.plist & Generate .icns (MacOS)
      if: ${{ matrix.os == 'macos-12' }}
      run: |
        plutil data/Info.plist
        mkdir csprite.iconset
        sips -z 16 16     data/icon-32x32.png --out csprite.iconset/icon_16x16.png
        sips -z 32 32     data/icon-32x32.png --out csprite.iconset/icon_16x16@2x.png
        sips -z 32 32     data/icon-32x32.png --out csprite.iconset/icon_32x32.png
        sips -z 64 64     data/icon-32x32.png --out csprite.iconset/icon_32x32@2x.png
        sips -z 128 128   data/icon-32x32.png --out csprite.iconset/icon_128x128.png
        sips -z 256 256   data/icon-32x32.png --out csprite.iconset/icon_128x128@2x.png
        sips -z 256 256   data/icon-32x32.png --out csprite.iconset/icon_256x256.png
        sips -z 512 512   data/icon-32x32.png --out csprite.iconset/icon_256x256@2x.png
        sips -z 512 512   data/icon-32x32.png --out csprite.iconset/icon_512x512.png
        sips -z 1024 1024 data/icon-32x32.png --out csprite.iconset/icon_512x512@2x.png
        iconutil -c icns -o csprite.icns csprite.iconset
        rm -R csprite.iconset

    - name: Install Python Deps
      run: |
        python3 -m pip install --upgrade Pillow
        python3 -m pip install --upgrade numpy

    - name: Generate Build Files & Build (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        export CC=${{ matrix.cc }}
        export CXX=${{ matrix.cxx }}
        export CXXFLAGS=${{ matrix.flags }}
        export CFLAGS=${{ matrix.flags }}
        export LDFLAGS=${{ matrix.flags }}
        make gen-assets
        make all GENERATOR=Ninja BUILD_TYPE=Release NUM_JOBS=4

    - name: Generate Build Files & Build (Windows)
      if: ${{ matrix.os == 'windows-2022' }}
      run: |
        make gen-assets CXX=clang++
        make all GENERATOR="${{ matrix.gen_cmake_name }}" BUILD_TYPE=Release NUM_JOBS=4 CMAKE_GEN_FLAGS='-A "${{ matrix.arch }}" -T "ClangCL"'

    - name: Generate Build Files, Build & Zip (MacOS)
      if: ${{ matrix.os == 'macos-12' }}
      run: |
        make gen-assets
        make all GENERATOR="${{ matrix.gen }}" BUILD_TYPE=Release NUM_JOBS=4 CMAKE_GEN_FLAGS='-DBUILD_APPLE_BUNDLE=ON -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}'

    - name: Upload Artifacts (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: actions/upload-artifact@v3
      with:
        name: linux-${{ matrix.arch }}
        path: ./build/csprite
        if-no-files-found: error

    - name: Upload artifacts (Windows)
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'windows-2022' }}
      with:
        name: win-${{ matrix.arch }}-${{ matrix.gen_short_name }}
        if-no-files-found: error
        path: ./build/Release/*

    - name: Upload Artifacts (MacOS)
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'macos-12' }}
      with:
        name: osx-${{ matrix.arch }}-${{ matrix.gen }}
        path: ./build/Release/csprite.app/
        if-no-files-found: error

  update-ci-release:
    needs: [build]
    permissions:
      contents: write
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        tag_name: latest-git
        delete_release: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/download-artifact@v3
      with:
        name: win-x64-vs17_2022
        path: ./win-x64-vs17_2022/

    - uses: actions/download-artifact@v3
      with:
        name: win-Win32-vs17_2022
        path: ./win-Win32-vs17_2022/

    - uses: actions/download-artifact@v3
      with:
        name: linux-X64
        path: ./linux-X64/

    - uses: actions/download-artifact@v3
      with:
        name: linux-x32
        path: ./linux-x32/

    - uses: actions/download-artifact@v3
      with:
        name: osx-arm64-Xcode
        path: ./osx-arm64-Xcode/

    - uses: actions/download-artifact@v3
      with:
        name: osx-x86_64-Xcode
        path: ./osx-x86_64-Xcode/

    - name: Rename
      run: |
        mv ./win-x64-vs17_2022/csprite.zip ./win-x64-vs17_2022.zip
        mv ./win-Win32-vs17_2022/csprite.zip ./win-x86-vs17_2022.zip

        mv ./linux-x64/csprite ./linux-x64
        mv ./linux-x32/csprite ./linux-x32

        mv ./osx-arm64-Xcode/csprite.zip ./osx-arm64-Xcode.zip
        mv ./osx-x86_64-Xcode/csprite.zip ./osx-x64-Xcode.zip

    - uses: ncipollo/release-action@v1
      with:
        name: "Csprite Latest Git"
        body: "this release is not for daily use."
        tag: "latest-git"
        commit: "master"
        prerelease: true
        allowUpdates: true
        generateReleaseNotes: true
        artifactErrorsFailBuild: true
        artifacts: |
          ./win-x64-vs17_2022.zip
          ./win-x86-vs17_2022.zip
          ./linux-x64
          ./linux-x32
          ./osx-arm64-Xcode.zip
          ./osx-x64-Xcode.zip
