name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-x86_64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build libsdl2-dev libsdl2-2.0-0

    - name: Generate Build Files & Build
      run: |
        cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -G "Ninja"
        cmake --build ./build/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: csprite-linux-x86_64
        path: ./build/csprite

  windows-x86_64:
    runs-on: windows-2022
    strategy:
      matrix:
        architecture: [x64, Win32]
        generator: [ { short_name: "vs17_2022", cmake_name: "Visual Studio 17 2022" } ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Instal SDL2
      run: |
        git clone https://github.com/libsdl-org/SDL/ -b release-2.26.5
        cd SDL/
        cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -G "${{ matrix.generator.cmake_name }}" -A "${{ matrix.architecture }}"
        cmake --build ./build/ --config Release --parallel
        cmake --install ./build/ --strip --config Release

    - name: Generate Build Files & Build
      run: |
        cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -G "${{ matrix.generator.cmake_name }}" -A "${{ matrix.architecture }}"
        cmake --build ./build/ --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: csprite-win-${{ matrix.architecture }}-${{ matrix.generator.short_name }}
        path: ./build/Release/csprite.exe

  macos-x86_64:
    runs-on: macos-12 # Monterey
    strategy:
      matrix:
        architecture: [x86_64, arm64]
        generator: [Xcode]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install SDL2
      run: |
        formulaResult=$(brew --cache --bottle-tag=${{ matrix.architecture }}_monterey sdl2)
        brew fetch --force --bottle-tag=${{ matrix.architecture }}_monterey sdl2
        brew install $formulaResult

#     - name: Instal SDL2
#       run: |
#         git clone https://github.com/libsdl-org/SDL/ -b release-2.26.5
#         cd SDL/
#         cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -G "${{ matrix.generator }}" -DCMAKE_OSX_ARCHITECTURES=${{ matrix.architecture }}
#         cmake --build ./build/ --config Release --parallel
#         cmake --install ./build/ --strip --config Release

    - name: Generate Build Files & Build
      run: |
        cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -G "${{ matrix.generator }}" -DCMAKE_OSX_ARCHITECTURES=${{ matrix.architecture }}
        cmake --build ./build/ --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: csprite-osx-${{ matrix.architecture }}-${{ matrix.generator }}
        path: ./build/Release/csprite


