name: Continous Build Action
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install GLFW3, Git & Scons
      run: |
        sudo apt-get install libglfw3 libglfw3-dev git scons

    - name: Build CSprite
      run: make release

    - name: Strip Debug Info
      run: strip ./csprite

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux_binary
        path: csprite
        if-no-files-found: error

  windows-x86_64:
    runs-on: windows-2019
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install Scons
      run: |
        python -m pip install --user scons

    - name: Build CSprite
      run: scons -j 2 mode=release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win_binary
        path: csprite.exe
        if-no-files-found: error
