name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  generate-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Generate Asset
      run: |
        python3 -m pip install --upgrade Pillow
        python3 -m pip install --upgrade numpy
        make gen-assets

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: data
        path: ./data/
        if-no-files-found: error

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: src-assets
        path: ./src/assets/
        if-no-files-found: error

  linux-x86_64:
    needs: [generate-assets]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/download-artifact@v2
      with:
        name: src-assets
        path: ./src/assets/

    - uses: actions/download-artifact@v2
      with:
        name: data
        path: ./data/

    - name: Build & Install SDL2
      run: bash ./tools/BuildNInstall_Linux.sh

    - name: Install Deps
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build zlib1g zlib1g-dev libfuse2
        wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.0-beta.1/appimage-builder-1.0.0-677acbd-x86_64.AppImage
        chmod +x appimage-builder-x86_64.AppImage
        sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder

    - name: Generate Build Files & Build
      run: |
        cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -G "Ninja"
        cmake --build ./build/
        mv ./build/csprite ./

    - name: Build AppImage
      run: |
        make appimage
        mv ./csprite-*.AppImage ./csprite-x86_64.AppImage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64-appimage
        path: csprite-x86_64.AppImage
        if-no-files-found: error

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ matrix.config.cc == 'clang' }}
      with:
        name: linux-x86_64
        path: ./csprite
        if-no-files-found: error

  windows-x86_64:
    needs: [generate-assets]
    runs-on: windows-2022
    strategy:
      matrix:
        architecture: [x64, Win32]
        generator: [ { short_name: "vs17_2022", cmake_name: "Visual Studio 17 2022" } ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/download-artifact@v2
      with:
        name: src-assets
        path: ./src/assets/

    - uses: actions/download-artifact@v2
      with:
        name: data
        path: ./data/

    - name: Build & Install ZLib
      run: |
        git clone https://github.com/madler/zlib/ --recursive -b v1.2.13
        cd zlib/
        cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -G "${{ matrix.generator.cmake_name }}" -A "${{ matrix.architecture }}"
        cmake --build ./build/ --config Release --parallel
        cmake --install ./build/ --strip --config Release

    - name: Build & Install SDL2
      run: |
        git clone https://github.com/libsdl-org/SDL/ -b release-2.26.5
        cd SDL/
        cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -G "${{ matrix.generator.cmake_name }}" -A "${{ matrix.architecture }}"
        cmake --build ./build/ --config Release --parallel
        cmake --install ./build/ --strip --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win-${{ matrix.architecture }}-${{ matrix.generator.short_name }}
        path: |
          ./build/Release/csprite.exe
          ./build/Release/*.dll

  osx_x86_64:
    needs: [generate-assets]
    runs-on: macos-12 # Monterey
    strategy:
      matrix:
        architecture: [x86_64, arm64]
        generator: [Xcode]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/download-artifact@v2
      with:
        name: src-assets
        path: ./src/assets/

    - uses: actions/download-artifact@v2
      with:
        name: data
        path: ./data/

    - name: Lint Info.plist
      run: plutil data/Info.plist

    - name: Install dylibbundler, SDL2 & zlib
      run: |
        PACKAGES=(dylibbundler sdl2 zlib)
        for PACKAGE in "${PACKAGES[@]}"
        do
          formulaResult=$(brew --cache --bottle-tag=${{ matrix.architecture }}_monterey $PACKAGE)
          brew fetch --force --bottle-tag=${{ matrix.architecture }}_monterey $PACKAGE
          brew install $formulaResult
        done

    - name: Generate .icns
      run: |
        mkdir csprite.iconset
        sips -z 16 16     data/icon-scaled.png --out csprite.iconset/icon_16x16.png
        sips -z 32 32     data/icon-scaled.png --out csprite.iconset/icon_16x16@2x.png
        sips -z 32 32     data/icon-scaled.png --out csprite.iconset/icon_32x32.png
        sips -z 64 64     data/icon-scaled.png --out csprite.iconset/icon_32x32@2x.png
        sips -z 128 128   data/icon-scaled.png --out csprite.iconset/icon_128x128.png
        sips -z 256 256   data/icon-scaled.png --out csprite.iconset/icon_128x128@2x.png
        sips -z 256 256   data/icon-scaled.png --out csprite.iconset/icon_256x256.png
        sips -z 512 512   data/icon-scaled.png --out csprite.iconset/icon_256x256@2x.png
        sips -z 512 512   data/icon-scaled.png --out csprite.iconset/icon_512x512.png
        cp data/icon-scaled.png csprite.iconset/icon_512x512@2x.png
        iconutil -c icns -o csprite.icns csprite.iconset
        rm -R csprite.iconset

    - name: Generate Build Files & Build
      run: |
        cmake -S ./ -B ./build/ -DCMAKE_BUILD_TYPE=Release -DBUILD_APPLE_BUNDLE=ON -G "${{ matrix.generator }}" -DCMAKE_OSX_ARCHITECTURES=${{ matrix.architecture }}
        cmake --build ./build/ --config Release

    - name: Create Zip
      run: zip -r csprite.zip ./build/Release/csprite.app/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: csprite-osx-${{ matrix.architecture }}-${{ matrix.generator }}
        path: ./csprite.zip
        if-no-files-found: error

  update-ci-release:
    needs: [linux-x86_64, windows-x86_64, osx_x86_64]
    permissions:
      contents: write
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        tag_name: latest-git
        delete_release: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: ncipollo/release-action@v1
      with:
        name: "Csprite Latest Git"
        body: "this release is not for daily use."
        tag: "latest-git"
        commit: "master"
        prerelease: true
        allowUpdates: true
        generateReleaseNotes: true
        artifactErrorsFailBuild: true

