name: nightly
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  generate-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Generate Asset
      run: |
        python3 -m pip install --upgrade Pillow
        python3 -m pip install --upgrade numpy
        make gen-assets

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: src-assets
        path: ./src/assets/
        if-no-files-found: error

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: data
        path: ./data/
        if-no-files-found: error

  linux-x86_64:
    needs: [generate-assets]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/download-artifact@v2
      with:
        name: src-assets
        path: ./src/assets/

    - uses: actions/download-artifact@v2
      with:
        name: data
        path: ./data/

    - name: Install Git & Scons
      run: |
        sudo apt-get install git scons

    - name: Build & Install SDL2
      run: ./tools/BuildNInstall.sh

    - name: Build
      run: make release

    - name: Strip
      run: strip ./csprite

    - name: Install AppImage Builder
      run: |
        wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.0-beta.1/appimage-builder-1.0.0-677acbd-x86_64.AppImage
        chmod +x appimage-builder-x86_64.AppImage
        sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder

    - name: Build AppImage
      run: make appimage

    - name: Build .tar.gz
      run: make targz

    - name: Rename
      run: mv ./csprite-*.tar.gz ./csprite-x86_64.tar.gz && mv ./csprite-*.AppImage ./csprite-x86_64.AppImage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: csprite-x86_64.tar.gz
        if-no-files-found: error

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64-appimage
        path: csprite-x86_64.AppImage
        if-no-files-found: error

  linux_i686:
    needs: [generate-assets]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/download-artifact@v2
      with:
        name: src-assets
        path: ./src/assets/

    - uses: actions/download-artifact@v2
      with:
        name: data
        path: ./data/

    - name: Setup Ubuntu 18.04 x86
      uses: paulproteus/ubuntu-18.04-x86@0.1
      with:
        command: |
          apt-get update -y
          apt-get install -y pkg-config git libgtk-3-dev scons clang
          git clone https://github.com/libsdl-org/SDL -b release-2.24.0
          ./tools/BuildNInstall.sh
          CC=clang make release

    - name: Exit if file not exists
      run: |
        if [ ! -e ./csprite-i686.elf ]; then
            echo "'csprite-i686.elf' executable not found"
            exit 1
        fi

    - name: Build .tar.gz
      run: make targz

    - name: Rename
      run: mv ./csprite-*.tar.gz ./csprite-i686.tar.gz

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-i686
        path: ./csprite-i686.tar.gz
        if-no-files-found: error

  windows-x86_64:
    needs: [generate-assets]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: mingw-w64-x86_64-clang mingw-w64-x86_64-SDL2 mingw-w64-x86_64-python scons make git

      - uses: actions/download-artifact@v2
        with:
          name: src-assets
          path: ./src/assets/

      - uses: actions/download-artifact@v2
        with:
          name: data
          path: ./data/

      - name: Generate RC
        run: |
          make gen-rc

      - name: Build & Rename
        run: |
          CC=clang make release
          mv csprite.exe csprite-x86_64.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win-x86_64
          path: csprite-x86_64.exe
          if-no-files-found: error

  windows-i686:
    needs: [generate-assets]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: mingw-w64-i686-binutils mingw-w64-i686-clang mingw-w64-i686-SDL2 mingw-w64-x86_64-python scons make git

      - uses: actions/download-artifact@v2
        with:
          name: src-assets
          path: ./src/assets/

      - uses: actions/download-artifact@v2
        with:
          name: data
          path: ./data/

      - name: Generate Assets
        run: |
          make gen-rc

      - name: Build & Rename
        run: |
          PATH=/mingw32/bin/:$PATH CC=clang make release
          mv csprite.exe csprite-i686.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win-i686
          path: csprite-i686.exe
          if-no-files-found: error

  osx_x86_64:
    needs: [generate-assets]
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install scons, dylibbundler & SDL2
      run: |
        brew install scons dylibbundler sdl2

    - uses: actions/download-artifact@v2
      with:
        name: src-assets
        path: ./src/assets/

    - uses: actions/download-artifact@v2
      with:
        name: data
        path: ./data/

    - name: Build
      run: make release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx_executable
        path: ./csprite
        if-no-files-found: error

    - name: Generate .icns
      run: |
        mkdir csprite.iconset
        sips -z 16 16     data/icon-512.png --out csprite.iconset/icon_16x16.png
        sips -z 32 32     data/icon-512.png --out csprite.iconset/icon_16x16@2x.png
        sips -z 32 32     data/icon-512.png --out csprite.iconset/icon_32x32.png
        sips -z 64 64     data/icon-512.png --out csprite.iconset/icon_32x32@2x.png
        sips -z 128 128   data/icon-512.png --out csprite.iconset/icon_128x128.png
        sips -z 256 256   data/icon-512.png --out csprite.iconset/icon_128x128@2x.png
        sips -z 256 256   data/icon-512.png --out csprite.iconset/icon_256x256.png
        sips -z 512 512   data/icon-512.png --out csprite.iconset/icon_256x256@2x.png
        sips -z 512 512   data/icon-512.png --out csprite.iconset/icon_512x512.png
        cp data/icon-512.png csprite.iconset/icon_512x512@2x.png
        iconutil -c icns -o csprite.icns csprite.iconset
        rm -R csprite.iconset

    - name: Create Apple Bundle
      run: |
        mkdir csprite.app
        mkdir csprite.app/Contents
        mkdir csprite.app/Contents/libs
        mkdir csprite.app/Contents/MacOS
        mkdir csprite.app/Contents/Resources
        cp ./csprite ./csprite.app/Contents/MacOS/
        cp ./csprite.icns ./csprite.app/Contents/Resources/csprite.icns
        cp ./data/Info.plist ./csprite.app/Contents/

    - name: Put Dylibs
      run: |
        dylibbundler -od -b -ns -x ./csprite.app/Contents/MacOS/csprite -d ./csprite.app/Contents/libs/

    - name: Create Zip
      run: zip -r csprite-osx.zip ./csprite.app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx_binary
        path: ./csprite-osx.zip
        if-no-files-found: error
