name: Stable Release Action
on: 
  workflow_dispatch:
    inputs:
      is_prerelease:
        description: "is this release a pre-release?"
        required: false
        default: false
        type: boolean 

      version: 
        type: string
        required: true
        description: 'Version number without "v" Eg: 0.12.2'

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install GLFW3 And Git
      run: |
        sudo apt-get install libglfw3
        sudo apt-get install libglfw3-dev
        sudo apt-get install git

    - name: Build CSprite
      run: make release -j4

    - name: Strip & Rename
      run: strip ./csprite && mv ./csprite ./csprite.elf

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux_binary
        path: csprite.elf
        if-no-files-found: error

  windows-x86_64:
    runs-on: windows-2019
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Build CSprite
      run: make release -j4

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win_binary
        path: csprite.exe
        if-no-files-found: error

  Create-Release:
    needs: [linux-x86_64, windows-x86_64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clean previous binaries
      run: rm -f csprite csprite.exe

    - name: Download Linux build artifacts
      uses: actions/download-artifact@v2
      with:
        name: linux_binary

    - name: Download Windows build artifacts
      uses: actions/download-artifact@v2
      with:
        name: win_binary

    - name: Update/Create Continous Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{github.event.inputs.version}}"
        prerelease: ${{github.event.inputs.is_prerelease}}
        title: "csprite v${{github.event.inputs.version}}"
        files: |
          csprite.elf
          csprite.exe
