name: Stable Release Action
on: 
  workflow_dispatch:
    inputs:
      is_prerelease:
        description: "is this release a pre-release?"
        required: false
        default: false
        type: boolean 

      version: 
        type: string
        required: true
        description: 'Version number without "v" Eg: 0.12.2'

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install GLFW3, Git, Scons & Pillow
      run: |
        sudo apt-get install libglfw3 libglfw3-dev git scons
        python3 -m pip install --upgrade Pillow
        python3 -m pip install --upgrade numpy

    - name: Generate Assets
      run: |
        python3 tools/create_icons.py
        python3 tools/create_assets.py

    - name: Build
      run: make release

    - name: Strip & Rename
      run: strip ./csprite && mv ./csprite csprite.elf

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux_binary
        path: csprite.elf
        if-no-files-found: error

  windows-x86_64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: mingw-w64-x86_64-clang mingw-w64-x86_64-glfw mingw-w64-x86_64-python mingw-w64-x86_64-python-numpy mingw-w64-x86_64-python-pillow scons make git

      - name: Generate Assets
        run: |
          python3 tools/create_icons.py
          python3 tools/create_assets.py

      - name: Build
        run: |
          CC=clang make release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win_binary
          path: csprite.exe
          if-no-files-found: error

  osx_x86_64:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install scons, dylibbundler, glfw3 & Pillow
      run: |
        brew install scons dylibbundler glfw
        python3 -m pip install --upgrade Pillow
        python3 -m pip install --upgrade numpy

    - name: Generate Assets
      run: |
        python3 tools/create_icons.py
        python3 tools/create_assets.py

    - name: Build
      run: make release

    - name: Generate .icns
      run: |
        mkdir csprite.iconset
        sips -z 16 16     data/icon-512.png --out csprite.iconset/icon_16x16.png
        sips -z 32 32     data/icon-512.png --out csprite.iconset/icon_16x16@2x.png
        sips -z 32 32     data/icon-512.png --out csprite.iconset/icon_32x32.png
        sips -z 64 64     data/icon-512.png --out csprite.iconset/icon_32x32@2x.png
        sips -z 128 128   data/icon-512.png --out csprite.iconset/icon_128x128.png
        sips -z 256 256   data/icon-512.png --out csprite.iconset/icon_128x128@2x.png
        sips -z 256 256   data/icon-512.png --out csprite.iconset/icon_256x256.png
        sips -z 512 512   data/icon-512.png --out csprite.iconset/icon_256x256@2x.png
        sips -z 512 512   data/icon-512.png --out csprite.iconset/icon_512x512.png
        cp data/icon-512.png csprite.iconset/icon_512x512@2x.png
        iconutil -c icns -o csprite.icns csprite.iconset
        rm -R csprite.iconset

    - name: Create Apple Bundle
      run: |
        mkdir csprite.app
        mkdir csprite.app/Contents
        mkdir csprite.app/Contents/libs
        mkdir csprite.app/Contents/MacOS
        mkdir csprite.app/Contents/Resources
        cp ./csprite ./csprite.app/Contents/MacOS/
        cp ./csprite.icns ./csprite.app/Contents/Resources/csprite.icns
        cp ./assets/Info.plist ./csprite.app/Contents/

    - name: Put Dylibs
      run: |
        dylibbundler -od -b -ns -x ./csprite.app/Contents/MacOS/csprite -d ./csprite.app/Contents/libs/

    - name: Create Zip
      run: zip -r csprite-osx.zip ./csprite.app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx_binary
        path: ./csprite-osx.zip
        if-no-files-found: error

  Create-Release:
    needs: [linux-x86_64, windows-x86_64, osx_x86_64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clean previous binaries
      run: rm -f csprite csprite.exe

    - uses: actions/download-artifact@v2
      with:
        name: linux_binary

    - uses: actions/download-artifact@v2
      with:
        name: win_binary

    - uses: actions/download-artifact@v2
      with:
        name: osx_binary

    - name: Update/Create Continous Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{github.event.inputs.version}}"
        prerelease: ${{github.event.inputs.is_prerelease}}
        title: "csprite v${{github.event.inputs.version}}"
        files: |
          csprite.elf
          csprite.exe
          csprite-osx.zip

